
let  dummy_data=[{"id":1,"address":"78 Miller Crossing","distance":2,"scooters_availible":7,"electric_cars":5},
{"id":2,"address":"22098 Dottie Avenue","distance":1,"scooters_availible":10,"electric_cars":5},
{"id":3,"address":"39 Bultman Lane","distance":4,"scooters_availible":9,"electric_cars":6},
{"id":4,"address":"66232 Armistice Court","distance":3,"scooters_availible":14,"electric_cars":2},
{"id":5,"address":"8243 Texas Pass","distance":1,"scooters_availible":10,"electric_cars":0},
{"id":6,"address":"2537 Kensington Center","distance":5,"scooters_availible":15,"electric_cars":7},
{"id":7,"address":"4 Morrow Park","distance":3,"scooters_availible":8,"electric_cars":4},
{"id":8,"address":"6 Continental Hill","distance":1,"scooters_availible":13,"electric_cars":5},
{"id":9,"address":"419 Grover Way","distance":2,"scooters_availible":24,"electric_cars":7},
{"id":10,"address":"0767 Harper Junction","distance":2,"scooters_availible":17,"electric_cars":2},
{"id":11,"address":"750 Crest Line Road","distance":1,"scooters_availible":5,"electric_cars":6},
{"id":12,"address":"160 Ilene Point","distance":1,"scooters_availible":9,"electric_cars":4},
{"id":13,"address":"3 Debra Plaza","distance":1,"scooters_availible":13,"electric_cars":3},
{"id":14,"address":"0822 Montana Crossing","distance":1,"scooters_availible":5,"electric_cars":4},
{"id":15,"address":"68 Bunker Hill Park","distance":3,"scooters_availible":12,"electric_cars":4},
{"id":16,"address":"93 Bluestem Drive","distance":1,"scooters_availible":11,"electric_cars":3},
{"id":17,"address":"84 Namekagon Avenue","distance":3,"scooters_availible":11,"electric_cars":7},
{"id":18,"address":"71 Vermont Parkway","distance":1,"scooters_availible":10,"electric_cars":5},
{"id":19,"address":"50 Esch Way","distance":1,"scooters_availible":16,"electric_cars":3},
{"id":20,"address":"8 Ridgeway Circle","distance":1,"scooters_availible":8,"electric_cars":6},
{"id":21,"address":"9 Westerfield Alley","distance":1,"scooters_availible":7,"electric_cars":5},
{"id":22,"address":"5 Old Shore Avenue","distance":1,"scooters_availible":6,"electric_cars":8},
{"id":23,"address":"021 Lukken Center","distance":1,"scooters_availible":11,"electric_cars":3},
{"id":24,"address":"45 Shasta Lane","distance":1,"scooters_availible":8,"electric_cars":2},
{"id":25,"address":"696 Bunker Hill Circle","distance":3,"scooters_availible":10,"electric_cars":7},
{"id":26,"address":"12 Shasta Street","distance":6,"scooters_availible":9,"electric_cars":3},
{"id":27,"address":"4 Almo Hill","distance":2,"scooters_availible":10,"electric_cars":2},
{"id":28,"address":"3 Carioca Court","distance":1,"scooters_availible":14,"electric_cars":6},
{"id":29,"address":"34489 Hintze Avenue","distance":4,"scooters_availible":11,"electric_cars":4},
{"id":30,"address":"091 Pepper Wood Center","distance":2,"scooters_availible":11,"electric_cars":7},
{"id":31,"address":"95 Charing Cross Park","distance":2,"scooters_availible":10,"electric_cars":3},
{"id":32,"address":"011 Lawn Circle","distance":1,"scooters_availible":10,"electric_cars":8},
{"id":33,"address":"6989 Stuart Place","distance":1,"scooters_availible":10,"electric_cars":10},
{"id":34,"address":"0 Katie Pass","distance":3,"scooters_availible":13,"electric_cars":8},
{"id":35,"address":"9241 Meadow Vale Crossing","distance":1,"scooters_availible":12,"electric_cars":7},
{"id":36,"address":"92 Clove Trail","distance":2,"scooters_availible":7,"electric_cars":5},
{"id":37,"address":"04927 Main Pass","distance":1,"scooters_availible":6,"electric_cars":5},
{"id":38,"address":"7 Elmside Trail","distance":4,"scooters_availible":15,"electric_cars":6},
{"id":39,"address":"8 Morningstar Point","distance":2,"scooters_availible":12,"electric_cars":6},
{"id":40,"address":"7 Summerview Point","distance":6,"scooters_availible":7,"electric_cars":2},
{"id":41,"address":"70 Morrow Plaza","distance":2,"scooters_availible":10,"electric_cars":3},
{"id":42,"address":"814 Menomonie Alley","distance":1,"scooters_availible":8,"electric_cars":6},
{"id":43,"address":"67877 Superior Terrace","distance":7,"scooters_availible":13,"electric_cars":5},
{"id":44,"address":"31017 Lakewood Point","distance":1,"scooters_availible":11,"electric_cars":4},
{"id":45,"address":"102 Harbort Street","distance":1,"scooters_availible":10,"electric_cars":7},
{"id":46,"address":"03 Scofield Point","distance":1,"scooters_availible":11,"electric_cars":4},
{"id":47,"address":"2 Hintze Street","distance":5,"scooters_availible":14,"electric_cars":8},
{"id":48,"address":"8351 Westerfield Plaza","distance":4,"scooters_availible":4,"electric_cars":2},
{"id":49,"address":"31749 Troy Lane","distance":2,"scooters_availible":5,"electric_cars":3},
{"id":50,"address":"44 Haas Hill","distance":2,"scooters_availible":8,"electric_cars":5},
{"id":51,"address":"77824 Dawn Trail","distance":2,"scooters_availible":9,"electric_cars":4},
{"id":52,"address":"1802 Hoard Court","distance":3,"scooters_availible":4,"electric_cars":6},
{"id":53,"address":"1528 Pankratz Circle","distance":1,"scooters_availible":7,"electric_cars":3},
{"id":54,"address":"8 Superior Alley","distance":1,"scooters_availible":12,"electric_cars":3},
{"id":55,"address":"3 Fuller Place","distance":6,"scooters_availible":9,"electric_cars":4},
{"id":56,"address":"5 Carberry Drive","distance":3,"scooters_availible":10,"electric_cars":7},
{"id":57,"address":"93 Cottonwood Court","distance":2,"scooters_availible":8,"electric_cars":6},
{"id":58,"address":"1898 Sunbrook Junction","distance":2,"scooters_availible":12,"electric_cars":8},
{"id":59,"address":"939 3rd Way","distance":3,"scooters_availible":8,"electric_cars":2},
{"id":60,"address":"198 Mayfield Park","distance":7,"scooters_availible":15,"electric_cars":7},
{"id":61,"address":"27 Scofield Court","distance":3,"scooters_availible":5,"electric_cars":8},
{"id":62,"address":"98 Dawn Pass","distance":2,"scooters_availible":3,"electric_cars":8},
{"id":63,"address":"991 Cottonwood Way","distance":1,"scooters_availible":9,"electric_cars":8},
{"id":64,"address":"42 Fisk Avenue","distance":1,"scooters_availible":11,"electric_cars":3},
{"id":65,"address":"33241 Lunder Lane","distance":3,"scooters_availible":10,"electric_cars":5},
{"id":66,"address":"92 Badeau Court","distance":1,"scooters_availible":13,"electric_cars":4},
{"id":67,"address":"6823 Vermont Point","distance":2,"scooters_availible":12,"electric_cars":3},
{"id":68,"address":"41 Anhalt Plaza","distance":4,"scooters_availible":9,"electric_cars":6},
{"id":69,"address":"471 Thierer Place","distance":1,"scooters_availible":11,"electric_cars":4},
{"id":70,"address":"69352 Monica Pass","distance":2,"scooters_availible":9,"electric_cars":4},
{"id":71,"address":"54 Pleasure Lane","distance":1,"scooters_availible":15,"electric_cars":6},
{"id":72,"address":"061 Scoville Point","distance":1,"scooters_availible":6,"electric_cars":4},
{"id":73,"address":"3505 Bluejay Point","distance":1,"scooters_availible":18,"electric_cars":2},
{"id":74,"address":"53 Bluejay Center","distance":2,"scooters_availible":10,"electric_cars":1},
{"id":75,"address":"944 Spenser Center","distance":1,"scooters_availible":6,"electric_cars":2},
{"id":76,"address":"030 Darwin Plaza","distance":1,"scooters_availible":8,"electric_cars":7},
{"id":77,"address":"9 Ilene Plaza","distance":3,"scooters_availible":13,"electric_cars":5},
{"id":78,"address":"53 Mcbride Junction","distance":2,"scooters_availible":14,"electric_cars":4},
{"id":79,"address":"9280 Troy Drive","distance":2,"scooters_availible":12,"electric_cars":7},
{"id":80,"address":"14 Florence Drive","distance":2,"scooters_availible":14,"electric_cars":5},
{"id":81,"address":"6 4th Trail","distance":1,"scooters_availible":7,"electric_cars":3},
{"id":82,"address":"74658 Pleasure Way","distance":2,"scooters_availible":12,"electric_cars":4},
{"id":83,"address":"6973 Schurz Parkway","distance":2,"scooters_availible":7,"electric_cars":6},
{"id":84,"address":"05585 Schurz Court","distance":2,"scooters_availible":18,"electric_cars":7},
{"id":85,"address":"6882 Stone Corner Street","distance":2,"scooters_availible":4,"electric_cars":6},
{"id":86,"address":"6857 4th Drive","distance":1,"scooters_availible":8,"electric_cars":6},
{"id":87,"address":"63 Cascade Road","distance":1,"scooters_availible":11,"electric_cars":7},
{"id":88,"address":"44 Mitchell Place","distance":1,"scooters_availible":14,"electric_cars":6},
{"id":89,"address":"980 Hagan Alley","distance":1,"scooters_availible":8,"electric_cars":8},
{"id":90,"address":"4 Ridgeview Avenue","distance":1,"scooters_availible":10,"electric_cars":0},
{"id":91,"address":"89877 Pankratz Place","distance":2,"scooters_availible":11,"electric_cars":3},
{"id":92,"address":"487 Sheridan Street","distance":1,"scooters_availible":11,"electric_cars":3},
{"id":93,"address":"635 Carberry Circle","distance":1,"scooters_availible":16,"electric_cars":1},
{"id":94,"address":"7 Northland Terrace","distance":1,"scooters_availible":8,"electric_cars":7},
{"id":95,"address":"6 Oak Valley Pass","distance":6,"scooters_availible":6,"electric_cars":3},
{"id":96,"address":"097 Stoughton Hill","distance":1,"scooters_availible":10,"electric_cars":5},
{"id":97,"address":"207 Tony Street","distance":1,"scooters_availible":7,"electric_cars":9},
{"id":98,"address":"81 Ruskin Drive","distance":1,"scooters_availible":11,"electric_cars":2},
{"id":99,"address":"5 Mcbride Crossing","distance":1,"scooters_availible":9,"electric_cars":4},
{"id":100,"address":"2 Wayridge Crossing","distance":1,"scooters_availible":10,"electric_cars":8}].sort((a,b)=> a.distance-b.distance )

export default dummy_data;